name: deploy-backend
on: 
  push:
    paths:
      - .github/workflows/deploy-backend.yaml
      - backend/**

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BACKEND_SSH_HOST }}
        username: ${{ secrets.BACKEND_SSH_USERNAME }}
        key: ${{ secrets.BACKEND_SSH_KEY }}
        port: ${{ secrets.BACKEND_SSH_PORT }}
        script:
          cd ~/isthisbuillshit.github.io/backend && git pull && make run-server
