name: deploy-backend
on: 
  push:
    paths:
      - .github/workflows/deploy-backend.yaml
      - backend/**

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BACKEND_SSH_HOST }}
        username: ${{ secrets.BACKEND_SSH_USERNAME }}
        password: ${{ secrets.BACKEND_SSH_PASSWORD }}
        port: ${{ secrets.BACKEND_SSH_PORT }}
        script:
          git clone git@github.com:isthisbullshit/isthisbuillshit.github.io.git
          cd isthisbuillshit.github.io.git/backend && git pull && make install-prod
