name: deploy-bsdetector
on: 
  push:
    paths:
      - Dockerfile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup ssh connection
        run: |
          echo "${{ secrets.BACKEND_SSH_KEY }}" > $(pwd)/private_key
          chmod 600 $(pwd)/private_key
          ssh -o "IdentitiesOnly=yes" -i $(pwd)/private_key -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -M -S server-socket -fnNT -L 12346:${{ secrets.BACKEND_SSH_HOST }}:5000 ${{ secrets.BACKEND_SSH_USERNAME }}@${{ secrets.BACKEND_SSH_HOST }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: 127.0.0.1:12346/bs-detector-2
      - name: teardown
        if: always()
        run: |
          ssh -S server-socket -O exit ${{ secrets.BACKEND_SSH_USERNAME }}@${{ secrets.BACKEND_SSH_HOST }}

