name: Deploy static content to digital ocean

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/deploy-frontend-2.yaml
      - frontend/**
  
  workflow_dispatch:

concurrency:
  group: "frontend-2"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tar files
        run: |
          tar czf frontend.tar.gz frontend
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BACKEND_SSH_HOST }}
          username: ${{ secrets.BACKEND_SSH_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          port: ${{ secrets.BACKEND_SSH_PORT }}
          source: frontend.tar.gz
          target: /

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BACKEND_SSH_HOST }}
          username: ${{ secrets.BACKEND_SSH_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          port: ${{ secrets.BACKEND_SSH_PORT }}
          script: |
            rm frontend -rf
            tar -xvzf frontend.tar.gz
            

